# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app_credentials: '%env(key:password:key:gmail:json:file:resolve:CREDENTIALS_FILE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
        #    $omdbToken: 28c5b7b1
        #    $omdbHost: https://www.omdbapi.com

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        # Ajouter ds les 'exclude' les objects qui ne doivent pas être des services
        # ou bien si vous voulez faire une déclaration explicite
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Déclaration partielle
    #App\OmdbApi:
    #    arguments:
    #        $omdbToken: 28c5b7b1
    #        $omdbHost: https://www.omdbapi.com

    # Déclaration explicite
    App\OmdbApi:
        arguments:
            $omdbToken: '%env(OMDB_TOKEN)%'
            $omdbHost: https://www.omdbapi.com
            $omdbClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'